trigger:
  branches:
    include:
    - main
  batch: True
resources:
  repositories:
  - repository: self
    type: git
    ref: main
parameters:
  - name: account
    type: string
    default: 5bd7e7ed-c091-4182-9caa-931ea7a13fe6
variables:
  USERNAME_TAG: $(UsernameTag)
  API_GATEWAY_RESOURCE_VINYLS_PATH_PART: $(APIGatewayResourceVinylsPathPart)
  LAMBDA_FUNC_UPDATE_NAME: $(LambdaFuncUPDATEName)
  LAMBDA_FUNC_DELETE_NAME: $(LambdaFuncDELETEName)
  LAMBDA_FUNC_GET_NAME: $(LambdaFuncGETName)
  LAMBDA_FUNC_POST_NAME: $(LambdaFuncPOSTName)
  DYNAMO_DB_TABLE_NAME: $(DynamoDBTableName)
  API_NAME: $(APIName)
  ENVIRONMENT_NAME: $(EnvironmentName)
  VINYL_STORE_CLOUDFRONT_S3_BUCKET_NAME: $(VinylStoreCloudFrontS3BucketName)
  VINYL_STORE_LAMBDA_GET_SCRIPT_NAME: $(VinylStoreLambdaGETScriptName)
  VINYL_STORE_LAMBDA_POST_SCRIPT_NAME: $(VinylStoreLambdaPOSTScriptName)
  VINYL_STORE_LAMBDA_DELETE_SCRIPT_NAME: $(VinylStoreLambdaDELETEScriptName)
  VINYL_STORE_LAMBDA_UPDATE_SCRIPT_NAME: $(VinylStoreLambdaUPDATEScriptName)
  VINYL_STORE_COGNITO_DOMAIN: $(VinylStoreCognitoDomain)
  DEPLOYMENT_ROLE_ACCESS_KEY_ID: $(DeploymentRoleAccessKeyId)
  DEPLOYMENT_ROLE_SECRET_ACCESS_KEY_ID: $(DeploymentRoleSecretAccessKeyId)
  MY_AWS_ROLE_ARN: $(MyAWSRoleARN)
jobs:
- job: 'Job_1'
  displayName: Agent job 1
  pool:
      vmImage: vs2017-win2016
  variables:
    - name: cfn-template
      value: '$(System.DefaultWorkingDirectory)/VinylStoreCF.yaml'
  steps:
      - checkout: self
        clean: true
      - task: CloudFormationCreateOrUpdateStack@1
        displayName: 'Create/Update Stack: plata-marquez-alvaro-VinylStore-stack'
        inputs:
          awsCredentials: '${{ parameters.account }}'
          regionName: 'us-east-1'
          stackName: plata-marquez-alvaro-VinylStore-stack
          templateSource: 'file'
          templateFile: '$(cfn-template)' 
          roleARN: arn:aws:iam::933005959117:role/CloudFormationADRole
          templateParametersSource: "inline"
          templateParameters: |
            - ParameterKey: UsernameTag
              ParameterValue: $(USERNAME_TAG)
            - ParameterKey: APIGatewayResourceVinylsPathPart
              ParameterValue: $(API_GATEWAY_RESOURCE_VINYLS_PATH_PART)
            - ParameterKey: LambdaFuncUPDATEName
              ParameterValue: $(LAMBDA_FUNC_UPDATE_NAME)
            - ParameterKey: LambdaFuncDELETEName
              ParameterValue: $(LAMBDA_FUNC_DELETE_NAME)
            - ParameterKey: LambdaFuncGETName
              ParameterValue: $(LAMBDA_FUNC_GET_NAME)
            - ParameterKey: LambdaFuncPOSTName
              ParameterValue: $(LAMBDA_FUNC_POST_NAME)
            - ParameterKey: DynamoDBTableName
              ParameterValue: $(DYNAMO_DB_TABLE_NAME)
            - ParameterKey: APIName
              ParameterValue: $(API_NAME)
            - ParameterKey: EnvironmentName
              ParameterValue: $(ENVIRONMENT_NAME)
            - ParameterKey: VinylStoreCloudFrontS3BucketName
              ParameterValue: $(VINYL_STORE_CLOUDFRONT_S3_BUCKET_NAME)
            - ParameterKey: VinylStoreLambdaGETScriptName
              ParameterValue: $(VINYL_STORE_LAMBDA_GET_SCRIPT_NAME)
            - ParameterKey: VinylStoreLambdaPOSTScriptName
              ParameterValue: $(VINYL_STORE_LAMBDA_POST_SCRIPT_NAME)
            - ParameterKey: VinylStoreLambdaDELETEScriptName
              ParameterValue: $(VINYL_STORE_LAMBDA_DELETE_SCRIPT_NAME)
            - ParameterKey: VinylStoreLambdaUPDATEScriptName
              ParameterValue: $(VINYL_STORE_LAMBDA_UPDATE_SCRIPT_NAME)
            - ParameterKey: VinylStoreCognitoDomain
              ParameterValue: $(VINYL_STORE_COGNITO_DOMAIN)
            - ParameterKey: DeploymentRoleAccessKeyId
              ParameterValue: $(DEPLOYMENT_ROLE_ACCESS_KEY_ID)
            - ParameterKey: DeploymentRoleSecretAccessKeyId
              ParameterValue: $(DEPLOYMENT_ROLE_SECRET_ACCESS_KEY_ID)
            - ParameterKey: MyAWSRoleARN
              ParameterValue: $(MY_AWS_ROLE_ARN)
          tags: '
          azure-devops:pipeline-id=$(System.DefinitionId)
          azure-devops:creator-email=$(Build.RequestedForEmail)
          azure-devops:repository=$(Build.Repository.Name)'
...
