trigger:
  branches:
    include:
    - main
  batch: True
resources:
  repositories:
  - repository: self
    type: git
    ref: main
parameters:
  - name: account
    type: string
    default: 5bd7e7ed-c091-4182-9caa-931ea7a13fe6
jobs:
- job: 'Job_1'
  displayName: Agent job 2
  pool:
      vmImage: vs2017-win2016
  variables:
    - name: cfn-template
      value: '$(System.DefaultWorkingDirectory)/VinylStoreCF.yaml'
  steps:
      - checkout: self
        clean: true
      - task: CloudFormationCreateOrUpdateStack@1
        displayName: 'Create/Update Stack: plata-marquez-alvaro-VinylStore-stack'
        inputs:
          awsCredentials: '${{ parameters.account }}'
          regionName: 'us-east-1'
          stackName: plata-marquez-alvaro-VinylStore-stack
          templateSource: 'file'
          templateFile: '$(cfn-template)' 
          roleARN: arn:aws:iam::933005959117:role/CloudFormationADRole
          templateParametersSource: "inline"
          templateParameters: |
            - ParameterKey: UsernameTag
              ParameterValue: $(Build.RequestedForEmail)
            - ParameterKey: APIGatewayResourceVinylsPathPart
              ParameterValue: $env:APIGatewayResourceVinylsPathPart
            - ParameterKey: LambdaFuncUPDATEName
              ParameterValue: $env:LambdaFuncUPDATEName
            - ParameterKey: LambdaFuncDELETEName
              ParameterValue: $env:LambdaFuncDELETEName
            - ParameterKey: LambdaFuncGETName
              ParameterValue: $env:LambdaFuncGETName
            - ParameterKey: LambdaFuncGETALLName
              ParameterValue: $env:LambdaFuncGETALLName
            - ParameterKey: LambdaFuncPOSTName
              ParameterValue: $env:LambdaFuncPOSTName
            - ParameterKey: DynamoDBTableName
              ParameterValue: $env:DynamoDBTableName
            - ParameterKey: APIName
              ParameterValue: $env:APIName
            - ParameterKey: EnvironmentName
              ParameterValue: $env:EnvironmentName
            - ParameterKey: MicroservicesS3BucketName
              ParameterValue: $env:MicroservicesS3BucketName
            - ParameterKey: DELETEMicroserviceS3BucketKey
              ParameterValue: $env:DELETEMicroserviceS3BucketKey
          tags: '
          azure-devops:pipeline-id=$(System.DefinitionId)
          azure-devops:creator-email=$(Build.RequestedForEmail)
          azure-devops:repository=$(Build.Repository.Name)'
...
